import { IWord } from "../redux/features/words/slices"

export const newWordsUnit1: IWord[] = [
  { word: "ひと(人)", meaning: "person", total: 0, right: 0, unit: 1 },
  { word: "いす(椅子)", meaning: "chair", total: 0, right: 0, unit: 1 },
  { word: "つくえ(机)", meaning: "desk", total: 0, right: 0, unit: 1 },
  { word: "かさ(傘)", meaning: "umbrella", total: 0, right: 0, unit: 1 },
  { word: "かばん(鞄)", meaning: "bag", total: 0, right: 0, unit: 1 },
  { word: "じしょ(辞書)", meaning: "dictionary", total: 0, right: 0, unit: 1 },
  { word: "しんぶん(新聞)", meaning: "newspaper", total: 0, right: 0, unit: 1 },
  { word: "テーブル", meaning: "table", total: 0, right: 0, unit: 1 },
  {
    word: "めいし(名刺)",
    meaning: "business card",
    total: 0,
    right: 0,
    unit: 1,
  },
  { word: "えんぴつ(鉛筆)", meaning: "pencil", total: 0, right: 0, unit: 1 },
  { word: "かぎ(鍵)", meaning: "key", total: 0, right: 0, unit: 1 },
  { word: "とけい(時計)", meaning: "clock", total: 0, right: 0, unit: 1 },
  { word: "テレビ", meaning: "television", total: 0, right: 0, unit: 1 },
  { word: "ほん(本)", meaning: "book", total: 0, right: 0, unit: 1 },
  {
    word: "しゃしん(写真)",
    meaning: "photograph",
    total: 0,
    right: 0,
    unit: 1,
  },
  { word: "カメラ", meaning: "camera", total: 0, right: 0, unit: 1 },
  { word: "くつ(靴)", meaning: "shoes", total: 0, right: 0, unit: 1 },
  { word: "めがね(眼鏡)", meaning: "glasses", total: 0, right: 0, unit: 1 },
  { word: "とおり(通り)", meaning: "street", total: 0, right: 0, unit: 1 },
  { word: "かど(角)", meaning: "corner", total: 0, right: 0, unit: 1 },
  {
    word: "ひるやすみ(昼休み)",
    meaning: "lunch break",
    total: 0,
    right: 0,
    unit: 1,
  },
  { word: "いえ(家)", meaning: "house", total: 0, right: 0, unit: 1 },
  {
    word: "れいぞうこ(冷蔵庫)",
    meaning: "refrigerator",
    total: 0,
    right: 0,
    unit: 1,
  },
  {
    word: "れんしゅう(練習)",
    meaning: "practice",
    total: 0,
    right: 0,
    unit: 1,
  },
  { word: "きっさてん(喫茶店)", meaning: "cafe", total: 0, right: 0, unit: 1 },
  { word: "ぎんこう(銀行)", meaning: "bank", total: 0, right: 0, unit: 1 },
  { word: "うりば(売り場)", meaning: "shop", total: 0, right: 0, unit: 1 },
  { word: "トイレ", meaning: "toilet", total: 0, right: 0, unit: 1 },
  {
    word: "えいがかん(映画館)",
    meaning: "movie theater",
    total: 0,
    right: 0,
    unit: 1,
  },
  {
    word: "じてんしゃ(自転車)",
    meaning: "bicycle",
    total: 0,
    right: 0,
    unit: 1,
  },
];

export const newWordsUnit2: IWord[] = [
  { word: "わたし(私)", meaning: "I, me", total: 0, right: 0, unit: 2 },
  { word: "あなた(貴方)", meaning: "you", total: 0, right: 0, unit: 2 },
  { word: "かれ(彼)", meaning: "he", total: 0, right: 0, unit: 2 },
  { word: "かのじょ(彼女)", meaning: "she", total: 0, right: 0, unit: 2 },
  {
    word: "そちら(其方)",
    meaning: "you (polite)",
    total: 0,
    right: 0,
    unit: 2,
  },
  { word: "わたしたち(私達)", meaning: "we", total: 0, right: 0, unit: 2 },
  {
    word: "あなたたち(貴方達)",
    meaning: "you (plural)",
    total: 0,
    right: 0,
    unit: 2,
  },
  { word: "かれら(彼等)", meaning: "they (male)", total: 0, right: 0, unit: 2 },
  {
    word: "かのじょたち(彼女達)",
    meaning: "they (female)",
    total: 0,
    right: 0,
    unit: 2,
  },
  { word: "これ(此れ)", meaning: "this", total: 0, right: 0, unit: 2 },
  { word: "それ(其れ)", meaning: "that", total: 0, right: 0, unit: 2 },
  {
    word: "あれ(彼れ)",
    meaning: "that (over there)",
    total: 0,
    right: 0,
    unit: 2,
  },
  { word: "どれ(何れ)", meaning: "which", total: 0, right: 0, unit: 2 },
  { word: "ここ(此処)", meaning: "here", total: 0, right: 0, unit: 2 },
  { word: "そこ(其処)", meaning: "there", total: 0, right: 0, unit: 2 },
  { word: "あそこ(彼処)", meaning: "over there", total: 0, right: 0, unit: 2 },
  { word: "どこ(何処)", meaning: "where", total: 0, right: 0, unit: 2 },
  { word: "だれ(誰)", meaning: "who", total: 0, right: 0, unit: 2 },
  { word: "なに(何)", meaning: "what", total: 0, right: 0, unit: 2 },
  { word: "いつ(何時)", meaning: "when", total: 0, right: 0, unit: 2 },
  { word: "どう(如何)", meaning: "how", total: 0, right: 0, unit: 2 },
  { word: "はい", meaning: "yes", total: 0, right: 0, unit: 2 },
  { word: "いいえ", meaning: "no", total: 0, right: 0, unit: 2 },
  {
    word: "ありがとう(有難う)",
    meaning: "thank you",
    total: 0,
    right: 0,
    unit: 2,
  },
  {
    word: "すみません(済みません)",
    meaning: "I'm sorry",
    total: 0,
    right: 0,
    unit: 2,
  },
  {
    word: "どういたしまして(如何致しまして)",
    meaning: "you're welcome",
    total: 0,
    right: 0,
    unit: 2,
  },
  {
    word: "おはよう(お早う)",
    meaning: "good morning",
    total: 0,
    right: 0,
    unit: 2,
  },
  {
    word: "こんにちは(今日は)",
    meaning: "good afternoon",
    total: 0,
    right: 0,
    unit: 2,
  },
  {
    word: "こんばんは(今晩は)",
    meaning: "good evening",
    total: 0,
    right: 0,
    unit: 2,
  },
  {
    word: "おやすみ(お休み)",
    meaning: "good night",
    total: 0,
    right: 0,
    unit: 2,
  },
];

export const newWordsUnit3: IWord[] = [
  { word: "ひと(人)", meaning: "person", total: 0, right: 0, unit: 3 },
  { word: "おみせ(店)", meaning: "store/shop", total: 0, right: 0, unit: 3 },
  { word: "べんきょう(勉強)", meaning: "study", total: 0, right: 0, unit: 3 },
  { word: "うち(家)", meaning: "home", total: 0, right: 0, unit: 3 },
  { word: "いえ(家)", meaning: "house", total: 0, right: 0, unit: 3 },
  { word: "かぞく(家族)", meaning: "family", total: 0, right: 0, unit: 3 },
  { word: "こども(子供)", meaning: "child", total: 0, right: 0, unit: 3 },
  {
    word: "しょくどう(食堂)",
    meaning: "dining hall",
    total: 0,
    right: 0,
    unit: 3,
  },
  { word: "がっこう(学校)", meaning: "school", total: 0, right: 0, unit: 3 },
  { word: "ともだち(友達)", meaning: "friend", total: 0, right: 0, unit: 3 },
  {
    word: "おとうさん(お父さん)",
    meaning: "father",
    total: 0,
    right: 0,
    unit: 3,
  },
  {
    word: "おかあさん(お母さん)",
    meaning: "mother",
    total: 0,
    right: 0,
    unit: 3,
  },
  {
    word: "おねえさん(お姉さん)",
    meaning: "older sister",
    total: 0,
    right: 0,
    unit: 3,
  },
  {
    word: "おにいさん(お兄さん)",
    meaning: "older brother",
    total: 0,
    right: 0,
    unit: 3,
  },
  {
    word: "いもうと(妹)",
    meaning: "younger sister",
    total: 0,
    right: 0,
    unit: 3,
  },
  {
    word: "おとうと(弟)",
    meaning: "younger brother",
    total: 0,
    right: 0,
    unit: 3,
  },
  { word: "あね(姉)", meaning: "older sister", total: 0, right: 0, unit: 3 },
  {
    word: "おとうと(弟)",
    meaning: "younger brother",
    total: 0,
    right: 0,
    unit: 3,
  },
  {
    word: "きょうだい(兄弟)",
    meaning: "siblings",
    total: 0,
    right: 0,
    unit: 3,
  },
  { word: "ゆうめい(有名)", meaning: "famous", total: 0, right: 0, unit: 3 },
  { word: "せんせい(先生)", meaning: "teacher", total: 0, right: 0, unit: 3 },
  { word: "がくせい(学生)", meaning: "student", total: 0, right: 0, unit: 3 },
  { word: "へや(部屋)", meaning: "room", total: 0, right: 0, unit: 3 },
  { word: "ひとり(一人)", meaning: "one person", total: 0, right: 0, unit: 3 },
  { word: "ふたり(二人)", meaning: "two people", total: 0, right: 0, unit: 3 },
  { word: "みんな(皆)", meaning: "everyone", total: 0, right: 0, unit: 3 },
  {
    word: "おんなのひと(女の人)",
    meaning: "woman",
    total: 0,
    right: 0,
    unit: 3,
  },
  { word: "おとこのひと(男の人)", meaning: "man", total: 0, right: 0, unit: 3 },
  { word: "りょうしん(両親)", meaning: "parents", total: 0, right: 0, unit: 3 },
  { word: "しんせつ(親切)", meaning: "kind", total: 0, right: 0, unit: 3 },
];
export const newWordsUnit4: IWord[] = [
  { word: "ひと(人)", meaning: "person", total: 0, right: 0, unit: 4 },
  { word: "かいしゃ(会社)", meaning: "company", total: 0, right: 0, unit: 4 },
  { word: "うち(家)", meaning: "house", total: 0, right: 0, unit: 4 },
  { word: "いえ(家)", meaning: "house", total: 0, right: 0, unit: 4 },
  { word: "あるく(歩く)", meaning: "to walk", total: 0, right: 0, unit: 4 },
  {
    word: "かかる(かかります)",
    meaning: "to take (time/money)",
    total: 0,
    right: 0,
    unit: 4,
  },
  { word: "かえる(帰る)", meaning: "to go back", total: 0, right: 0, unit: 4 },
  { word: "かりる(借りる)", meaning: "to borrow", total: 0, right: 0, unit: 4 },
  {
    word: "うります(売ります)",
    meaning: "to sell",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "かいます(買います)",
    meaning: "to buy",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "とります(取ります)",
    meaning: "to take",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "とどけます(届けます)",
    meaning: "to deliver",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "すわります(座ります)",
    meaning: "to sit",
    total: 0,
    right: 0,
    unit: 4,
  },
  { word: "ねます(寝ます)", meaning: "to sleep", total: 0, right: 0, unit: 4 },
  {
    word: "べんきょうします(勉強します)",
    meaning: "to study",
    total: 0,
    right: 0,
    unit: 4,
  },
  { word: "みます(見ます)", meaning: "to see", total: 0, right: 0, unit: 4 },
  {
    word: "ききます(聞きます)",
    meaning: "to listen",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "しります(知ります)",
    meaning: "to know",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "しめます(閉めます)",
    meaning: "to close",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "あけます(開けます)",
    meaning: "to open",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "おしえます(教えます)",
    meaning: "to teach",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "はなします(話します)",
    meaning: "to speak",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "いそぎます(急ぎます)",
    meaning: "to hurry",
    total: 0,
    right: 0,
    unit: 4,
  },
  { word: "まつ(待つ)", meaning: "to wait", total: 0, right: 0, unit: 4 },
  {
    word: "でかけます(出かけます)",
    meaning: "to go out",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "かけます(掛けます)",
    meaning: "to hang",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "はしります(走ります)",
    meaning: "to run",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "はたらきます(働きます)",
    meaning: "to work",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "けんかします(喧嘩します)",
    meaning: "to quarrel",
    total: 0,
    right: 0,
    unit: 4,
  },
  {
    word: "わかれます(別れます)",
    meaning: "to separate",
    total: 0,
    right: 0,
    unit: 4,
  },
];



