import { IWord } from "../redux/features/words/slices";
import { ETopic } from "../types/topic.types";

export const vocabularyFamily: IWord[] = [
  {
    word: "ひと",
    kanji: "人",
    meaning: "person",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "かぞく",
    kanji: "家族",
    meaning: "family",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "おとうさん",
    kanji: "お父さん",
    meaning: "father",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "おかあさん",
    kanji: "お母さん",
    meaning: "mother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "あに",
    kanji: "兄",
    meaning: "older brother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "あね",
    kanji: "姉",
    meaning: "older sister",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "おとうと",
    kanji: "弟",
    meaning: "younger brother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "いもうと",
    kanji: "妹",
    meaning: "younger sister",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "こども",
    kanji: "子供",
    meaning: "child",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "むすこ",
    kanji: "息子",
    meaning: "son",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "むすめ",
    kanji: "娘",
    meaning: "daughter",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "じいさん",
    kanji: "祖父さん",
    meaning: "grandfather",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "ばあさん",
    kanji: "祖母さん",
    meaning: "grandmother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "いとこ",
    kanji: "いとこ",
    meaning: "cousin",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
];
export const vocabularyWeather: IWord[] = [
  {
    word: "てんき",
    kanji: "天気",
    meaning: "weather",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "あめ",
    kanji: "雨",
    meaning: "rain",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "ゆき",
    kanji: "雪",
    meaning: "snow",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "くもり",
    kanji: "曇り",
    meaning: "cloudy",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "はれ",
    kanji: "晴れ",
    meaning: "sunny",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "かぜ",
    kanji: "風",
    meaning: "wind",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "かみなり",
    kanji: "雷",
    meaning: "thunder",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "たいふう",
    kanji: "台風",
    meaning: "typhoon",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "あらし",
    kanji: "嵐",
    meaning: "storm",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "あらし",
    kanji: "嵐",
    meaning: "storm",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
];
export const vocabularyFood: IWord[] = [
  {
    word: "ごはん",
    kanji: "ご飯",
    meaning: "rice",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "さかな",
    kanji: "魚",
    meaning: "fish",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "にく",
    kanji: "肉",
    meaning: "meat",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "やさい",
    kanji: "野菜",
    meaning: "vegetable",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "くだもの",
    kanji: "果物",
    meaning: "fruit",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "パン",
    kanji: "パン",
    meaning: "bread",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "たまご",
    kanji: "卵",
    meaning: "egg",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "チーズ",
    kanji: "チーズ",
    meaning: "cheese",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ヨーグルト",
    kanji: "ヨーグルト",
    meaning: "yogurt",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "うどん",
    kanji: "うどん",
    meaning: "udon noodles",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "そば",
    kanji: "そば",
    meaning: "soba noodles",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ラーメン",
    kanji: "ラーメン",
    meaning: "ramen",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ピザ",
    kanji: "ピザ",
    meaning: "pizza",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ハンバーガー",
    kanji: "ハンバーガー",
    meaning: "hamburger",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ステーキ",
    kanji: "ステーキ",
    meaning: "steak",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "カレー",
    kanji: "カレー",
    meaning: "curry",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おにぎり",
    kanji: "お握り",
    meaning: "rice ball",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "すし",
    kanji: "寿司",
    meaning: "sushi",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "てんぷら",
    kanji: "天ぷら",
    meaning: "tempura",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おかし",
    kanji: "お菓子",
    meaning: "snack",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "アイスクリーム",
    kanji: "アイスクリーム",
    meaning: "ice cream",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "フルーツ",
    kanji: "フルーツ",
    meaning: "fruit",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "サラダ",
    kanji: "サラダ",
    meaning: "salad",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "コーヒー",
    kanji: "コーヒー",
    meaning: "coffee",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おちゃ",
    kanji: "お茶",
    meaning: "tea",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ビール",
    kanji: "ビール",
    meaning: "beer",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ワイン",
    kanji: "ワイン",
    meaning: "wine",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ジュース",
    kanji: "ジュース",
    meaning: "juice",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "みず",
    kanji: "水",
    meaning: "water",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おさけ",
    kanji: "お酒",
    meaning: "alcohol",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "やきにく",
    kanji: "焼き肉",
    meaning: "grilled meat",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "きんにく",
    kanji: "筋肉",
    meaning: "muscle",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "てんぷら",
    kanji: "天ぷら",
    meaning: "tempura",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "やきとり",
    kanji: "焼き鳥",
    meaning: "grilled chicken",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おすし",
    kanji: "お寿司",
    meaning: "sushi",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "そば",
    kanji: "蕎麦",
    meaning: "buckwheat noodles",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "たこやき",
    kanji: "たこ焼き",
    meaning: "octopus balls",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "とんかつ",
    kanji: "とんかつ",
    meaning: "pork cutlet",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "うなぎ",
    kanji: "鰻",
    meaning: "eel",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "そうめん",
    kanji: "素麺",
    meaning: "somen noodles",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ちらし",
    kanji: "ちらし寿司",
    meaning: "scattered sushi",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ひつまぶし",
    kanji: "ひつまぶし",
    meaning: "eel over rice",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おでん",
    kanji: "おでん",
    meaning: "oden",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "かれー",
    kanji: "カレー",
    meaning: "curry",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おこわ",
    kanji: "おこわ",
    meaning: "steamed rice cake",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "なべ",
    kanji: "鍋",
    meaning: "hot pot",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "すきやき",
    kanji: "すき焼き",
    meaning: "sukiyaki",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "しゃぶしゃぶ",
    kanji: "しゃぶしゃぶ",
    meaning: "shabu-shabu",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
];
export const vocabularyTransportation: IWord[] = [
  {
    word: "くるま",
    kanji: "車",
    meaning: "car",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "じてんしゃ",
    kanji: "自転車",
    meaning: "bicycle",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "でんしゃ",
    kanji: "電車",
    meaning: "train",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "バス",
    kanji: "バス",
    meaning: "bus",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "てんしゃ",
    kanji: "電車",
    meaning: "tram",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "くうこう",
    kanji: "空港",
    meaning: "airport",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "ふね",
    kanji: "船",
    meaning: "boat",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
];

export const vocabularyShopping: IWord[] = [
  {
    word: "かいもの",
    kanji: "買い物",
    meaning: "shopping",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "デパート",
    kanji: "デパート",
    meaning: "department store",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "しょうしょ",
    kanji: "商店",
    meaning: "shop",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "えいが",
    kanji: "映画",
    meaning: "movie",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "みせ",
    kanji: "店",
    meaning: "store",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "レストラン",
    kanji: "レストラン",
    meaning: "restaurant",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "スーパー",
    kanji: "スーパー",
    meaning: "supermarket",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "レジ",
    kanji: "レジ",
    meaning: "cash register",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
];

export const vocabularySports: IWord[] = [
  {
    word: "スポーツ",
    kanji: "スポーツ",
    meaning: "sports",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "サッカー",
    kanji: "サッカー",
    meaning: "soccer",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "テニス",
    kanji: "テニス",
    meaning: "tennis",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "バスケットボール",
    kanji: "バスケットボール",
    meaning: "basketball",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "バレーボール",
    kanji: "バレーボール",
    meaning: "volleyball",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "野球",
    kanji: "野球",
    meaning: "baseball",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "ゴルフ",
    kanji: "ゴルフ",
    meaning: "golf",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "スキー",
    kanji: "スキー",
    meaning: "skiing",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "スケート",
    kanji: "スケート",
    meaning: "skating",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "サーフィン",
    kanji: "サーフィン",
    meaning: "surfing",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
];

export const vocabularySchool: IWord[] = [
  {
    word: "がっこう",
    kanji: "学校",
    meaning: "school",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "せんせい",
    kanji: "先生",
    meaning: "teacher",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "がくせい",
    kanji: "学生",
    meaning: "student",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "きょうしつ",
    kanji: "教室",
    meaning: "classroom",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "ほん",
    kanji: "本",
    meaning: "book",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "とけい",
    kanji: "時計",
    meaning: "clock",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "ペン",
    kanji: "ペン",
    meaning: "pen",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "ノート",
    kanji: "ノート",
    meaning: "notebook",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "しけん",
    kanji: "試験",
    meaning: "exam",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "かばん",
    kanji: "鞄",
    meaning: "bag",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
];

export const vocabularyJobs: IWord[] = [
  {
    word: "しごと",
    kanji: "仕事",
    meaning: "job",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "かいしゃいん",
    kanji: "会社員",
    meaning: "company employee",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "せんせい",
    kanji: "先生",
    meaning: "teacher",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "いしゃ",
    kanji: "医者",
    meaning: "doctor",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "けんちくか",
    kanji: "建築家",
    meaning: "architect",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "かしゅ",
    kanji: "歌手",
    meaning: "singer",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "えいがか",
    kanji: "映画家",
    meaning: "filmmaker",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "べんごし",
    kanji: "弁護士",
    meaning: "lawyer",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "こうむいん",
    kanji: "公務員",
    meaning: "public servant",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "だいがくきょうし",
    kanji: "大学教師",
    meaning: "university professor",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
];

export const vocabularyAnimals: IWord[] = [
  {
    word: "どうぶつ",
    kanji: "動物",
    meaning: "animal",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "いぬ",
    kanji: "犬",
    meaning: "dog",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ねこ",
    kanji: "猫",
    meaning: "cat",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "うさぎ",
    kanji: "うさぎ",
    meaning: "rabbit",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "とり",
    kanji: "鳥",
    meaning: "bird",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "さる",
    kanji: "猿",
    meaning: "monkey",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ぞう",
    kanji: "象",
    meaning: "elephant",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ひつじ",
    kanji: "羊",
    meaning: "sheep",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ねずみ",
    kanji: "鼠",
    meaning: "mouse",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "うし",
    kanji: "牛",
    meaning: "cow",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
];

export const vocabularyItems: IWord[] = [
  {
    word: "もの",
    kanji: "物",
    meaning: "thing",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "えんぴつ",
    kanji: "鉛筆",
    meaning: "pencil",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "ペン",
    kanji: "ペン",
    meaning: "pen",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "ほん",
    kanji: "本",
    meaning: "book",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "かさ",
    kanji: "傘",
    meaning: "umbrella",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "とけい",
    kanji: "時計",
    meaning: "watch",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "でんしゃ",
    kanji: "電車",
    meaning: "train",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "くるま",
    kanji: "車",
    meaning: "car",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "てちょう",
    kanji: "手帳",
    meaning: "notebook",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "けしゴム",
    kanji: "消しゴム",
    meaning: "eraser",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "かぎ",
    kanji: "鍵",
    meaning: "key",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
];

export const vocabularyProfessions: IWord[] = [
  {
    word: "かいしゃいん",
    kanji: "会社員",
    meaning: "company employee",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "せんせい",
    kanji: "先生",
    meaning: "teacher",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "べんごし",
    kanji: "弁護士",
    meaning: "lawyer",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "いしゃ",
    kanji: "医者",
    meaning: "doctor",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "けんちくか",
    kanji: "建築家",
    meaning: "architect",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "かしゅ",
    kanji: "歌手",
    meaning: "singer",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "かいがいりょこうがいしゃいん",
    kanji: "海外旅行会社員",
    meaning: "travel agency employee",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "エンジニア",
    kanji: "エンジニア",
    meaning: "engineer",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "パイロット",
    kanji: "パイロット",
    meaning: "pilot",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "おかしや",
    kanji: "お菓子屋",
    meaning: "confectioner",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
];

export const vocabularySubjects: IWord[] = [
  {
    word: "れきし",
    kanji: "歴史",
    meaning: "history",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "さんすう",
    kanji: "算数",
    meaning: "mathematics",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "けいざい",
    kanji: "経済",
    meaning: "economics",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "りか",
    kanji: "理科",
    meaning: "science",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "ぶんがく",
    kanji: "文学",
    meaning: "literature",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "かがく",
    kanji: "化学",
    meaning: "chemistry",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "ぎじゅつ",
    kanji: "技術",
    meaning: "technology",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "えいご",
    kanji: "英語",
    meaning: "English",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "にほんご",
    kanji: "日本語",
    meaning: "Japanese",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "じょうほうがく",
    kanji: "情報学",
    meaning: "informatics",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
];

export const vocabularyPlaces: IWord[] = [
  {
    word: "えき",
    kanji: "駅",
    meaning: "station",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "こうえん",
    kanji: "公園",
    meaning: "park",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "うみ",
    kanji: "海",
    meaning: "sea",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "いえ",
    kanji: "家",
    meaning: "house",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "やま",
    kanji: "山",
    meaning: "mountain",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "ほんや",
    kanji: "本屋",
    meaning: "bookstore",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "びょういん",
    kanji: "病院",
    meaning: "hospital",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "えいがかん",
    kanji: "映画館",
    meaning: "movie theater",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "まち",
    kanji: "町",
    meaning: "town",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "うみべ",
    kanji: "海辺",
    meaning: "beach",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "けいさつしょ",
    kanji: "警察署",
    meaning: "police station",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "ぎんこう",
    kanji: "銀行",
    meaning: "bank",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "ゆうびんきょく",
    kanji: "郵便局",
    meaning: "post office",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "きっさてん",
    kanji: "喫茶店",
    meaning: "cafe",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "くうこう",
    kanji: "空港",
    meaning: "airport",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "びじゅつかん",
    kanji: "美術館",
    meaning: "art museum",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "としょかん",
    kanji: "図書館",
    meaning: "library",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "ゆうびんばんごう",
    kanji: "郵便番号",
    meaning: "postal code",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "ぎょえん",
    kanji: "魚園",
    meaning: "aquarium",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "びじんかん",
    kanji: "美人館",
    meaning: "beauty salon",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
];

export const vocabularyNumbers: IWord[] = [
  {
    word: "じゅういち",
    kanji: "十一",
    meaning: "eleven;11",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "にじゅう",
    kanji: "二十",
    meaning: "twenty;20",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さんじゅう",
    kanji: "三十",
    meaning: "thirty;30",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "よんじゅう",
    kanji: "四十",
    meaning: "forty;40",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ごじゅう",
    kanji: "五十",
    meaning: "fifty;50",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ろくじゅう",
    kanji: "六十",
    meaning: "sixty;60",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ななじゅう",
    kanji: "七十",
    meaning: "seventy;70",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "はちじゅう",
    kanji: "八十",
    meaning: "eighty;80",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "きゅうじゅう",
    kanji: "九十",
    meaning: "ninety;90",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ひゃくいち",
    kanji: "百一",
    meaning: "one hundred one;101",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さんびゃくごじゅうに",
    kanji: "三百五十二",
    meaning: "three hundred fifty-two;352",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "せんはっぴゃくじゅう",
    kanji: "千八百十",
    meaning: "one thousand eight hundred ten;1810",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ごせん",
    kanji: "五千",
    meaning: "five thousand;5000",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ななせんごひゃく",
    kanji: "七千五百",
    meaning: "seven thousand five hundred;7500",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "じゅうまん",
    kanji: "十万",
    meaning: "one hundred thousand;100000",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さんびゃくまん",
    kanji: "三百万",
    meaning: "three million;3000000",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "いち",
    kanji: "一",
    meaning: "one;1",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "に",
    kanji: "二",
    meaning: "two;2",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さん",
    kanji: "三",
    meaning: "three;3",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "し",
    kanji: "四",
    meaning: "four;4",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ご",
    kanji: "五",
    meaning: "five;5",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ろく",
    kanji: "六",
    meaning: "six;6",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "しち",
    kanji: "七",
    meaning: "seven;7",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "はち",
    kanji: "八",
    meaning: "eight;8",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "きゅう",
    kanji: "九",
    meaning: "nine;9",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "じゅう",
    kanji: "十",
    meaning: "ten;10",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ひゃく",
    kanji: "百",
    meaning: "hundred;100",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "せん",
    kanji: "千",
    meaning: "thousand;1000",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "まん",
    kanji: "万",
    meaning: "ten thousand;10000",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "おく",
    kanji: "億",
    meaning: "hundred million;100000000",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "てん",
    kanji: "点",
    meaning: "point",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ぜろ",
    kanji: "零",
    meaning: "zero;0",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
];

export const vocabularyColors: IWord[] = [
  {
    word: "あか",
    kanji: "赤",
    meaning: "red",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "あお",
    kanji: "青",
    meaning: "blue",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "きいろ",
    kanji: "黄色",
    meaning: "yellow",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "みどり",
    kanji: "緑",
    meaning: "green",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "しろ",
    kanji: "白",
    meaning: "white",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "くろ",
    kanji: "黒",
    meaning: "black",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "むらさき",
    kanji: "紫",
    meaning: "purple",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "ピンク",
    kanji: "ピンク",
    meaning: "pink",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "オレンジ",
    kanji: "オレンジ",
    meaning: "orange",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "ブラウン",
    kanji: "ブラウン",
    meaning: "brown",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
];

export const vocabularyTime: IWord[] = [
  {
    word: "じかん",
    kanji: "時間",
    meaning: "time",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ひ",
    kanji: "日",
    meaning: "day",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "しゅう",
    kanji: "週",
    meaning: "week",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "つき",
    kanji: "月",
    meaning: "month",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ねん",
    kanji: "年",
    meaning: "year",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "あさ",
    kanji: "朝",
    meaning: "morning",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ひる",
    kanji: "昼",
    meaning: "noon",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ばん",
    kanji: "晩",
    meaning: "evening",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ごご",
    kanji: "午後",
    meaning: "afternoon",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ごぜん",
    kanji: "午前",
    meaning: "morning",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "げつようび",
    kanji: "月曜日",
    meaning: "Monday",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "かようび",
    kanji: "火曜日",
    meaning: "Tuesday",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "すいようび",
    kanji: "水曜日",
    meaning: "Wednesday",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "もくようび",
    kanji: "木曜日",
    meaning: "Thursday",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "きんようび",
    kanji: "金曜日",
    meaning: "Friday",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "どようび",
    kanji: "土曜日",
    meaning: "Saturday",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "にちようび",
    kanji: "日曜日",
    meaning: "Sunday",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ついたち",
    kanji: "一日",
    meaning: "the first day of the month",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ふつか",
    kanji: "二日",
    meaning: "the second day of the month",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "みっか",
    kanji: "三日",
    meaning: "the third day of the month",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "よっか",
    kanji: "四日",
    meaning: "the fourth day of the month",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
];

export const vocabularyCountry: IWord[] = [
  {
    word: "くに",
    kanji: "国",
    meaning: "country",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "にほん",
    kanji: "日本",
    meaning: "Japan",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "アメリカ",
    kanji: "アメリカ",
    meaning: "America",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "イギリス",
    kanji: "イギリス",
    meaning: "England",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "フランス",
    kanji: "フランス",
    meaning: "France",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "ドイツ",
    kanji: "ドイツ",
    meaning: "Germany",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "かんこく",
    kanji: "韓国",
    meaning: "Korea",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "ちゅうごく",
    kanji: "中国",
    meaning: "China",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "イタリア",
    kanji: "イタリア",
    meaning: "Italy",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "スペイン",
    kanji: "スペイン",
    meaning: "Spain",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "ロシア",
    kanji: "ロシア",
    meaning: "Russia",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "かんしん",
    kanji: "韓国",
    meaning: "Korea",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "ブラジル",
    kanji: "ブラジル",
    meaning: "Brazil",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "カナダ",
    kanji: "カナダ",
    meaning: "Canada",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "オーストラリア",
    kanji: "オーストラリア",
    meaning: "Australia",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "インド",
    kanji: "インド",
    meaning: "India",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "メキシコ",
    kanji: "メキシコ",
    meaning: "Mexico",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "タイ",
    kanji: "タイ",
    meaning: "Thailand",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "インドネシア",
    kanji: "インドネシア",
    meaning: "Indonesia",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "フィリピン",
    kanji: "フィリピン",
    meaning: "Philippines",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "ベトナム",
    kanji: "ベトナム",
    meaning: "Vietnam",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "モロッコ",
    kanji: "モロッコ",
    meaning: "Morocco",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "サウジアラビア",
    kanji: "サウジアラビア",
    meaning: "Saudi Arabia",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
  {
    word: "エジプト",
    kanji: "エジプト",
    meaning: "Egypt",
    total: 0,
    right: 0,
    topic: ETopic.COUNTRY,
  },
];

export const vocabularyTechnology: IWord[] = [
  {
    word: "パソコン",
    kanji: "パソコン",
    meaning: "personal computer",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "スマートフォン",
    kanji: "スマートフォン",
    meaning: "smartphone",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "インターネット",
    kanji: "インターネット",
    meaning: "internet",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "ウェブサイト",
    kanji: "ウェブサイト",
    meaning: "website",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "メール",
    kanji: "メール",
    meaning: "email",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "アプリ",
    kanji: "アプリ",
    meaning: "app",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "パスワード",
    kanji: "パスワード",
    meaning: "password",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "カメラ",
    kanji: "カメラ",
    meaning: "camera",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "ビデオ",
    kanji: "ビデオ",
    meaning: "video",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "テレビ",
    kanji: "テレビ",
    meaning: "television",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "ゲーム",
    kanji: "ゲーム",
    meaning: "game",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "ネットワーク",
    kanji: "ネットワーク",
    meaning: "network",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "ソフトウェア",
    kanji: "ソフトウェア",
    meaning: "software",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "ハードウェア",
    kanji: "ハードウェア",
    meaning: "hardware",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "データ",
    kanji: "データ",
    meaning: "data",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
  {
    word: "バックアップ",
    kanji: "バックアップ",
    meaning: "backup",
    total: 0,
    right: 0,
    topic: ETopic.TECHNOLOGY,
  },
];

export const vocabularyTaste: IWord[] = [
  {
    word: "あまい",
    kanji: "甘い",
    meaning: "sweet",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "からい",
    kanji: "辛い",
    meaning: "spicy",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "しおからい",
    kanji: "塩辛い",
    meaning: "salty",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "すっぱい",
    kanji: "酸っぱい",
    meaning: "sour",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "にがい",
    kanji: "苦い",
    meaning: "bitter",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "うまい",
    kanji: "うまい",
    meaning: "delicious",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "まずい",
    kanji: "まずい",
    meaning: "bad-tasting",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "おいしい",
    kanji: "おいしい",
    meaning: "tasty",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "じゃがいも",
    kanji: "じゃがいも",
    meaning: "potato",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "にんじん",
    kanji: "人参",
    meaning: "carrot",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "たまねぎ",
    kanji: "玉ねぎ",
    meaning: "onion",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "にく",
    kanji: "肉",
    meaning: "meat",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "さかな",
    kanji: "魚",
    meaning: "fish",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "くだもの",
    kanji: "果物",
    meaning: "fruit",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "やさい",
    kanji: "野菜",
    meaning: "vegetable",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "あじ",
    kanji: "味",
    meaning: "flavor",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "かおり",
    kanji: "香り",
    meaning: "aroma",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "しょうゆ",
    kanji: "しょうゆ",
    meaning: "soy sauce",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "みそ",
    kanji: "味噌",
    meaning: "miso",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "しお",
    kanji: "塩",
    meaning: "salt",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "さとう",
    kanji: "砂糖",
    meaning: "sugar",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "にくやき",
    kanji: "肉焼き",
    meaning: "grilled meat",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "すし",
    kanji: "寿司",
    meaning: "sushi",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "たこやき",
    kanji: "たこ焼き",
    meaning: "octopus balls",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "てんぷら",
    kanji: "天ぷら",
    meaning: "tempura",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "ゆでたまご",
    kanji: "ゆでたまご",
    meaning: "boiled egg",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "みず",
    kanji: "水",
    meaning: "water",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "おちゃ",
    kanji: "お茶",
    meaning: "tea",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "こうちゃ",
    kanji: "紅茶",
    meaning: "black tea",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "ほうじちゃ",
    kanji: "ほうじ茶",
    meaning: "roasted green tea",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "こーら",
    kanji: "コーラ",
    meaning: "cola",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "みるく",
    kanji: "ミルク",
    meaning: "milk",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "みず",
    kanji: "水",
    meaning: "water",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "しんせんな",
    kanji: "新鮮な",
    meaning: "fresh",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "にんにく",
    kanji: "にんにく",
    meaning: "garlic",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "めんたいこ",
    kanji: "明太子",
    meaning: "spicy cod roe",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "しょうが",
    kanji: "しょうが",
    meaning: "ginger",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "からし",
    kanji: "からし",
    meaning: "mustard",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "わさび",
    kanji: "わさび",
    meaning: "wasabi",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "あく",
    kanji: "酸っぱい",
    meaning: "sour",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "かおる",
    kanji: "香る",
    meaning: "fragrant",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "くさい",
    kanji: "臭い",
    meaning: "smelly",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
  {
    word: "からい",
    kanji: "辛い",
    meaning: "hot (spicy)",
    total: 0,
    right: 0,
    topic: ETopic.TASTE,
  },
];
export const vocabularyFeeling: IWord[] = [
  {
    word: "うれしい",
    kanji: "嬉しい",
    meaning: "happy",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "かなしい",
    kanji: "悲しい",
    meaning: "sad",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "こわい",
    kanji: "怖い",
    meaning: "scared",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "はずかしい",
    kanji: "恥ずかしい",
    meaning: "embarrassed",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "きんちょうする",
    kanji: "緊張する",
    meaning: "nervous",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "いたい",
    kanji: "痛い",
    meaning: "painful",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "くやしい",
    kanji: "悔しい",
    meaning: "frustrated",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "さびしい",
    kanji: "寂しい",
    meaning: "lonely",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "いかり",
    kanji: "怒り",
    meaning: "angry",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "あんしん",
    kanji: "安心",
    meaning: "relieved",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "あきらめる",
    kanji: "諦める",
    meaning: "resigned",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "きまりいい",
    kanji: "気持ちいい",
    meaning: "comfortable",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "くすぐったい",
    kanji: "くすぐったい",
    meaning: "ticklish",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "ほっとする",
    kanji: "ほっとする",
    meaning: "relieved",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "うらやましい",
    kanji: "羨ましい",
    meaning: "envious",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "うとうとする",
    kanji: "うとうとする",
    meaning: "drowsy",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "ざんねん",
    kanji: "残念",
    meaning: "disappointed",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "はらがいたい",
    kanji: "腹が痛い",
    meaning: "stomachache",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "おおはしゃぎ",
    kanji: "大はしゃぎ",
    meaning: "excited",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "とまどう",
    kanji: "戸惑う",
    meaning: "confused",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "おそれる",
    kanji: "恐れる",
    meaning: "afraid",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "うんざり",
    kanji: "うんざり",
    meaning: "fed up",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "のろのろする",
    kanji: "のろのろする",
    meaning: "sluggish",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "ざわざわする",
    kanji: "ざわざわする",
    meaning: "nervous",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "きまずい",
    kanji: "気まずい",
    meaning: "awkward",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "たいくつ",
    kanji: "退屈",
    meaning: "bored",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "ほがらか",
    kanji: "ほがらか",
    meaning: "cheerful",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "ひんしゅく",
    kanji: "憤慨",
    meaning: "indignant",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
  {
    word: "ゆううつ",
    kanji: "憂鬱",
    meaning: "depressed",
    total: 0,
    right: 0,
    topic: ETopic.FELLING,
  },
];
export const vocabularyMusic: IWord[] = [
  {
    word: "おんがく",
    kanji: "音楽",
    meaning: "music",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "うた",
    kanji: "歌",
    meaning: "song",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "がっき",
    kanji: "楽器",
    meaning: "musical instrument",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "ピアノ",
    kanji: "ピアノ",
    meaning: "piano",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "ギター",
    kanji: "ギター",
    meaning: "guitar",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "ヴァイオリン",
    kanji: "ヴァイオリン",
    meaning: "violin",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "トランペット",
    kanji: "トランペット",
    meaning: "trumpet",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "フルート",
    kanji: "フルート",
    meaning: "flute",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "ドラム",
    kanji: "ドラム",
    meaning: "drum",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "バイオリン",
    kanji: "バイオリン",
    meaning: "violin",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "トロンボーン",
    kanji: "トロンボーン",
    meaning: "trombone",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "ハーモニカ",
    kanji: "ハーモニカ",
    meaning: "harmonica",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "オルガン",
    kanji: "オルガン",
    meaning: "organ",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "ベース",
    kanji: "ベース",
    meaning: "bass",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "マイク",
    kanji: "マイク",
    meaning: "microphone",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "コンサート",
    kanji: "コンサート",
    meaning: "concert",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "アルバム",
    kanji: "アルバム",
    meaning: "album",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "アーティスト",
    kanji: "アーティスト",
    meaning: "artist",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "バンド",
    kanji: "バンド",
    meaning: "band",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
  {
    word: "メロディー",
    kanji: "メロディー",
    meaning: "melody",
    total: 0,
    right: 0,
    topic: ETopic.MUSIC,
  },
];

export const vocabularyMovie: IWord[] = [
  {
    word: "えいが",
    kanji: "映画",
    meaning: "movie",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "がっこうえいが",
    kanji: "学校映画",
    meaning: "educational film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "かんぱんえいが",
    kanji: "感犯映画",
    meaning: "pornographic film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "きねんびえいが",
    kanji: "記念日映画",
    meaning: "commemorative film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "げきえい",
    kanji: "劇映",
    meaning: "drama",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "じしんえいが",
    kanji: "自信映画",
    meaning: "self-confidence film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "しゃちょうえいが",
    kanji: "社長映画",
    meaning: "company president film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "しんえんえいが",
    kanji: "新円映画",
    meaning: "new yen film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "すずえいが",
    kanji: "鈴映画",
    meaning: "bell film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "せいふえいが",
    kanji: "政府映画",
    meaning: "government film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "じごくえいが",
    kanji: "地獄映画",
    meaning: "hell film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "ともだちえいが",
    kanji: "友達映画",
    meaning: "friend film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "なつやすみえいが",
    kanji: "夏休み映画",
    meaning: "summer vacation film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "はらえいが",
    kanji: "原映画",
    meaning: "original film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "まるえいが",
    kanji: "丸映画",
    meaning: "circle film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "やくざえいが",
    kanji: "ヤクザ映画",
    meaning: "yakuza film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "おとこえいが",
    kanji: "男映画",
    meaning: "men's film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "おねえさんえいが",
    kanji: "お姉さん映画",
    meaning: "big sister movie",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "じぎょうえいが",
    kanji: "事業映画",
    meaning: "business film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
  {
    word: "じせいえいが",
    kanji: "自生映画",
    meaning: "self-produced film",
    total: 0,
    right: 0,
    topic: ETopic.MOVIE,
  },
];

const vocabularyHouseholdItems: IWord[] = [
  {
    word: "いす",
    kanji: "椅子",
    meaning: "chair",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "テーブル",
    kanji: "テーブル",
    meaning: "table",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "とけい",
    kanji: "時計",
    meaning: "clock",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ほんだな",
    kanji: "本棚",
    meaning: "bookshelf",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ねこ",
    kanji: "猫",
    meaning: "cat",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "いぬ",
    kanji: "犬",
    meaning: "dog",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ほん",
    kanji: "本",
    meaning: "book",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "パソコン",
    kanji: "パソコン",
    meaning: "computer",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "でんき",
    kanji: "電気",
    meaning: "electricity",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ほんだな",
    kanji: "本棚",
    meaning: "bookshelf",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ひかり",
    kanji: "光",
    meaning: "light",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ドア",
    kanji: "ドア",
    meaning: "door",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "まど",
    kanji: "窓",
    meaning: "window",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ふとん",
    kanji: "布団",
    meaning: "futon",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "いえ",
    kanji: "家",
    meaning: "house",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "ねかご",
    kanji: "寝かご",
    meaning: "crib",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "れいぞうこ",
    kanji: "冷蔵庫",
    meaning: "refrigerator",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "こたつ",
    kanji: "こたつ",
    meaning: "heated table",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "テレビ",
    kanji: "テレビ",
    meaning: "television",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
  {
    word: "せんたくき",
    kanji: "洗濯機",
    meaning: "washing machine",
    total: 0,
    right: 0,
    topic: ETopic.HOUSEHOLD_ITEMS,
  },
];

const vocabularyMenu: IWord[] = [
  {
    word: "ごはん",
    kanji: "御飯",
    meaning: "cooked rice",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "めん",
    kanji: "麺",
    meaning: "noodles",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "そば",
    kanji: "蕎麦",
    meaning: "buckwheat noodles",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "うどん",
    kanji: "うどん",
    meaning: "udon noodles",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "そうめん",
    kanji: "そうめん",
    meaning: "somen noodles",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "おにぎり",
    kanji: "お握り",
    meaning: "rice ball",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "やきとり",
    kanji: "焼き鳥",
    meaning: "grilled chicken skewers",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "おすし",
    kanji: "お寿司",
    meaning: "sushi",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "てんぷら",
    kanji: "天ぷら",
    meaning: "tempura",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "すきやき",
    kanji: "すき焼き",
    meaning: "sukiyaki",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "しゃぶしゃぶ",
    kanji: "しゃぶしゃぶ",
    meaning: "shabu-shabu",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "たこやき",
    kanji: "たこ焼き",
    meaning: "octopus balls",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "おでん",
    kanji: "おでん",
    meaning: "oden",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "らーめん",
    kanji: "らーめん",
    meaning: "ramen",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "とんかつ",
    kanji: "とんかつ",
    meaning: "pork cutlet",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "かつどん",
    kanji: "カツ丼",
    meaning: "pork cutlet bowl",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "カレーライス",
    kanji: "カレーライス",
    meaning: "curry rice",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "おちゃ",
    kanji: "お茶",
    meaning: "tea",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "ビール",
    kanji: "ビール",
    meaning: "beer",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
  {
    word: "ワイン",
    kanji: "ワイン",
    meaning: "wine",
    total: 0,
    right: 0,
    topic: ETopic.MENU,
  },
];
export const vocabularyTown: IWord[] = [
  {
    word: "まち",
    kanji: "町",
    meaning: "town",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "くうこう",
    kanji: "空港",
    meaning: "airport",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "えき",
    kanji: "駅",
    meaning: "station",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "ひこうき",
    kanji: "飛行機",
    meaning: "airplane",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "でんしゃ",
    kanji: "電車",
    meaning: "train",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "ばす",
    kanji: "バス",
    meaning: "bus",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "タクシー",
    kanji: "タクシー",
    meaning: "taxi",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "ホテル",
    kanji: "ホテル",
    meaning: "hotel",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "いえ",
    kanji: "家",
    meaning: "house",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "アパート",
    kanji: "アパート",
    meaning: "apartment",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "みせ",
    kanji: "店",
    meaning: "shop",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "レストラン",
    kanji: "レストラン",
    meaning: "restaurant",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "こうえん",
    kanji: "公園",
    meaning: "park",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "ぎんこう",
    kanji: "銀行",
    meaning: "bank",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "としょかん",
    kanji: "図書館",
    meaning: "library",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "えいがかん",
    kanji: "映画館",
    meaning: "movie theater",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "びょういん",
    kanji: "病院",
    meaning: "hospital",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "ひょうじょう",
    kanji: "表情",
    meaning: "post office",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "くうこうえき",
    kanji: "空港駅",
    meaning: "airport station",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "しんこう",
    kanji: "信号",
    meaning: "traffic light",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "みなと",
    kanji: "港",
    meaning: "harbor",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "たてもの",
    kanji: "建物",
    meaning: "building",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "しょうぼうしょ",
    kanji: "消防署",
    meaning: "fire station",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "こうばん",
    kanji: "交番",
    meaning: "police box",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
  {
    word: "コンビニ",
    kanji: "コンビニ",
    meaning: "convenience store",
    total: 0,
    right: 0,
    topic: ETopic.TOWN,
  },
];

export const vocabularyTrainStation = [
  {
    word: "えき",
    kanji: "駅",
    meaning: "station",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "でんしゃ",
    kanji: "電車",
    meaning: "train",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "のりば",
    kanji: "乗り場",
    meaning: "platform",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "きっぷ",
    kanji: "切符",
    meaning: "ticket",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "ひき",
    kanji: "引き",
    meaning: "fare",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "きっぷうりば",
    kanji: "切符売り場",
    meaning: "ticket counter",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "みどりのまど",
    kanji: "緑の窓",
    meaning: "green window (where tickets are sold)",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "えきいん",
    kanji: "駅員",
    meaning: "station attendant",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "ちか",
    kanji: "地下",
    meaning: "underground",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "のぼりば",
    kanji: "上り場",
    meaning: "up escalator",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "くだりば",
    kanji: "下り場",
    meaning: "down escalator",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "じどうはんば",
    kanji: "自動販売機",
    meaning: "vending machine",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "ホーム",
    kanji: "ホーム",
    meaning: "platform",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "のぼり",
    kanji: "上り",
    meaning: "upbound (train)",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "くだり",
    kanji: "下り",
    meaning: "downbound (train)",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "こうつう",
    kanji: "交通",
    meaning: "traffic",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "みち",
    kanji: "道",
    meaning: "road",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "ちかてつ",
    kanji: "地下鉄",
    meaning: "subway",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "りょうしん",
    kanji: "両親",
    meaning: "parents",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "おとうさん",
    kanji: "お父さん",
    meaning: "father",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "おかあさん",
    kanji: "お母さん",
    meaning: "mother",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "こども",
    kanji: "子供",
    meaning: "child",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "きょうだい",
    kanji: "兄弟",
    meaning: "siblings",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "ともだち",
    kanji: "友達",
    meaning: "friend",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
  {
    word: "ひとり",
    kanji: "一人",
    meaning: "one person",
    total: 0,
    right: 0,
    topic: ETopic.TRAIN_STATION,
  },
];
const vocabularyHealth: IWord[] = [
  {
    word: "けが",
    kanji: "怪我",
    meaning: "injury",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "びょうき",
    kanji: "病気",
    meaning: "illness",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "かぜ",
    kanji: "風邪",
    meaning: "cold",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "ねつ",
    kanji: "熱",
    meaning: "fever",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "げり",
    kanji: "下痢",
    meaning: "diarrhea",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "ほね",
    kanji: "骨",
    meaning: "bone",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "ほしゅ",
    kanji: "包帯",
    meaning: "bandage",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "いしゅ",
    kanji: "医療",
    meaning: "medical care",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "けんこう",
    kanji: "健康",
    meaning: "health",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "ふくしゅう",
    kanji: "復習",
    meaning: "review",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "やくそく",
    kanji: "約束",
    meaning: "promise",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "しゅじゅつ",
    kanji: "手術",
    meaning: "surgery",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "けいたいでんわ",
    kanji: "携帯電話",
    meaning: "cell phone",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "いんしゅつ",
    kanji: "印刷",
    meaning: "printing",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "ぎゃく",
    kanji: "逆",
    meaning: "reverse",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "しあわせ",
    kanji: "幸せ",
    meaning: "happiness",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "ほし",
    kanji: "星",
    meaning: "star",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "かがく",
    kanji: "科学",
    meaning: "science",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "じしん",
    kanji: "地震",
    meaning: "earthquake",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "けしょう",
    kanji: "化粧",
    meaning: "makeup",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "そうじ",
    kanji: "掃除",
    meaning: "cleaning",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "くすり",
    kanji: "薬",
    meaning: "medicine",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "いたみ",
    kanji: "痛み",
    meaning: "pain",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "せんたく",
    kanji: "洗濯",
    meaning: "laundry",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "あたま",
    kanji: "頭",
    meaning: "head",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "しばい",
    kanji: "芝居",
    meaning: "play (theatrical)",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "ねむり",
    kanji: "眠り",
    meaning: "sleep",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "あたまいたい",
    kanji: "頭痛い",
    meaning: "headache",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "わかれる",
    kanji: "別れる",
    meaning: "separate",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "せいふく",
    kanji: "制服",
    meaning: "uniform",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "きびしい",
    kanji: "厳しい",
    meaning: "strict",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "めまい",
    kanji: "めまい",
    meaning: "dizziness",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "しんぱい",
    kanji: "心配",
    meaning: "worry",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "きけん",
    kanji: "危険",
    meaning: "danger",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
  {
    word: "つぎ",
    kanji: "次",
    meaning: "next",
    total: 0,
    right: 0,
    topic: ETopic.HEALTH,
  },
];
const vocabularyMovement: IWord[] = [
  {
    word: "あるく",
    kanji: "歩く",
    meaning: "to walk",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "はしる",
    kanji: "走る",
    meaning: "to run",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "とぶ",
    kanji: "飛ぶ",
    meaning: "to fly",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "およぐ",
    kanji: "泳ぐ",
    meaning: "to swim",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "のる",
    kanji: "乗る",
    meaning: "to ride",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "うごく",
    kanji: "動く",
    meaning: "to move",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "まがる",
    kanji: "曲がる",
    meaning: "to turn",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "とまる",
    kanji: "止まる",
    meaning: "to stop",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "ひく",
    kanji: "引く",
    meaning: "to pull",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "おしえる",
    kanji: "教える",
    meaning: "to push",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "もつ",
    kanji: "持つ",
    meaning: "to carry",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "はこぶ",
    kanji: "運ぶ",
    meaning: "to transport",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "けす",
    kanji: "消す",
    meaning: "to extinguish",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "とおる",
    kanji: "通る",
    meaning: "to pass through",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "はなれる",
    kanji: "離れる",
    meaning: "to separate",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "かえる",
    kanji: "帰る",
    meaning: "to return",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "いく",
    kanji: "行く",
    meaning: "to go",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "くる",
    kanji: "来る",
    meaning: "to come",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "いる",
    kanji: "居る",
    meaning: "to be (animate)",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "ある",
    kanji: "有る",
    meaning: "to be (inanimate)",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "うごく",
    kanji: "動く",
    meaning: "to be in motion",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "すわる",
    kanji: "座る",
    meaning: "to sit",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "たつ",
    kanji: "立つ",
    meaning: "to stand",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "のぼる",
    kanji: "登る",
    meaning: "to climb",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "くだる",
    kanji: "下る",
    meaning: "to descend",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "すべる",
    kanji: "滑る",
    meaning: "to slide",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "はねる",
    kanji: "跳ねる",
    meaning: "to jump",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "おりる",
    kanji: "降りる",
    meaning: "to get off",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "のる",
    kanji: "乗る",
    meaning: "to get on",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "すわる",
    kanji: "座る",
    meaning: "to sit down",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "たつ",
    kanji: "立つ",
    meaning: "to stand up",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "うごかす",
    kanji: "動かす",
    meaning: "to move (something)",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "いる",
    kanji: "居る",
    meaning: "to be present",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
  {
    word: "ある",
    kanji: "有る",
    meaning: "to exist",
    total: 0,
    right: 0,
    topic: ETopic.MOVEMENT,
  },
];
const vocabularyClothing: IWord[] = [
  {
    word: "セーター",
    kanji: "",
    meaning: "sweater",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "シャツ",
    kanji: "",
    meaning: "shirt",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ズボン",
    kanji: "",
    meaning: "pants",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ジーンズ",
    kanji: "",
    meaning: "jeans",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ワンピース",
    kanji: "",
    meaning: "dress",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "スカート",
    kanji: "",
    meaning: "skirt",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ショーツ",
    kanji: "",
    meaning: "shorts",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "コート",
    kanji: "",
    meaning: "coat",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ジャケット",
    kanji: "",
    meaning: "jacket",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "タイ",
    kanji: "",
    meaning: "tie",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ベルト",
    kanji: "",
    meaning: "belt",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "くつ",
    kanji: "靴",
    meaning: "shoes",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "めがね",
    kanji: "眼鏡",
    meaning: "glasses",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "てぶくろ",
    kanji: "手袋",
    meaning: "gloves",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ぼうし",
    kanji: "帽子",
    meaning: "hat",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ネクタイ",
    kanji: "",
    meaning: "necktie",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ハンカチ",
    kanji: "",
    meaning: "handkerchief",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ズック",
    kanji: "",
    meaning: "socks",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "くつした",
    kanji: "靴下",
    meaning: "socks",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ショーツ",
    kanji: "",
    meaning: "shorts",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "パンツ",
    kanji: "",
    meaning: "underpants",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ワイシャツ",
    kanji: "",
    meaning: "white shirt",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "せびろ",
    kanji: "背広",
    meaning: "suit",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ふくろ",
    kanji: "袋",
    meaning: "bag",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "かばん",
    kanji: "鞄",
    meaning: "bag",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "たとう",
    kanji: "塔",
    meaning: "tower",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "かさ",
    kanji: "傘",
    meaning: "umbrella",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "ゆびわ",
    kanji: "指輪",
    meaning: "ring",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
  {
    word: "かめん",
    kanji: "仮面",
    meaning: "mask",
    total: 0,
    right: 0,
    topic: ETopic.CLOTHES,
  },
];
export const vocabularyHumanLife: IWord[] = [
  {
    word: "こども",
    kanji: "子供",
    meaning: "child",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "おとな",
    kanji: "大人",
    meaning: "adult",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "しゅうしょく",
    kanji: "就職",
    meaning: "employment",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "そつぎょう",
    kanji: "卒業",
    meaning: "graduation",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "けっこん",
    kanji: "結婚",
    meaning: "marriage",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "りこん",
    kanji: "離婚",
    meaning: "divorce",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "おとこ",
    kanji: "男",
    meaning: "man",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "おんな",
    kanji: "女",
    meaning: "woman",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "かぞく",
    kanji: "家族",
    meaning: "family",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "しんせつ",
    kanji: "親切",
    meaning: "kindness",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "けいかん",
    kanji: "警官",
    meaning: "police officer",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "けいこう",
    kanji: "景色",
    meaning: "scenery",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "しごと",
    kanji: "仕事",
    meaning: "work",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "たいいく",
    kanji: "体育",
    meaning: "physical education",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "ちゅうがくせい",
    kanji: "中学生",
    meaning: "junior high school student",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "せんせい",
    kanji: "先生",
    meaning: "teacher",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "かいしゃ",
    kanji: "会社",
    meaning: "company",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "けんきゅうしつ",
    kanji: "研究室",
    meaning: "research lab",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "しゅうまつ",
    kanji: "週末",
    meaning: "weekend",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "かんごし",
    kanji: "看護師",
    meaning: "nurse",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "ふたご",
    kanji: "双子",
    meaning: "twins",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "がっきゅう",
    kanji: "学級",
    meaning: "classroom",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "りょうしん",
    kanji: "両親",
    meaning: "parents",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "かお",
    kanji: "顔",
    meaning: "face",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "たんじょうび",
    kanji: "誕生日",
    meaning: "birthday",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "しごと",
    kanji: "仕事",
    meaning: "job",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "ともだち",
    kanji: "友達",
    meaning: "friend",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "かんぽう",
    kanji: "寒波",
    meaning: "cold wave",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "とし",
    kanji: "年",
    meaning: "year",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
  {
    word: "じんせい",
    kanji: "人生",
    meaning: "life",
    total: 0,
    right: 0,
    topic: ETopic.HUMAN_LIFE,
  },
];

export const vocabularyVerbs: IWord[] = [
  // N5 Verbs
  { word: "する", meaning: "to do", total: 0, right: 0, topic: ETopic.VERBS },
  { word: "いく", meaning: "to go", total: 0, right: 0, topic: ETopic.VERBS },
  { word: "くる", meaning: "to come", total: 0, right: 0, topic: ETopic.VERBS },
  { word: "みる", meaning: "to see", total: 0, right: 0, topic: ETopic.VERBS },
  {
    word: "あるく",
    meaning: "to walk",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "たべる",
    meaning: "to eat",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "のむ",
    meaning: "to drink",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "ねる",
    meaning: "to sleep",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "きく",
    meaning: "to listen",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  { word: "よむ", meaning: "to read", total: 0, right: 0, topic: ETopic.VERBS },
  // N4 Verbs
  { word: "かう", meaning: "to buy", total: 0, right: 0, topic: ETopic.VERBS },
  {
    word: "うたう",
    meaning: "to sing",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "かく",
    meaning: "to write",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "はなす",
    meaning: "to speak",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "およぐ",
    meaning: "to swim",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "あびる",
    meaning: "to take a shower",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "あるく",
    meaning: "to walk",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "たべる",
    meaning: "to eat",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "のむ",
    meaning: "to drink",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "ねる",
    meaning: "to sleep",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  // N3 Verbs
  {
    word: "あるく",
    meaning: "to walk",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "たべる",
    meaning: "to eat",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "のむ",
    meaning: "to drink",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "ねる",
    meaning: "to sleep",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "きく",
    meaning: "to listen",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  { word: "よむ", meaning: "to read", total: 0, right: 0, topic: ETopic.VERBS },
  { word: "かう", meaning: "to buy", total: 0, right: 0, topic: ETopic.VERBS },
  {
    word: "うたう",
    meaning: "to sing",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "かく",
    meaning: "to write",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  {
    word: "はなす",
    meaning: "to speak",
    total: 0,
    right: 0,
    topic: ETopic.VERBS,
  },
  // Add more verbs as needed
];
export const vocabularyN5: IWord[] = [
  // Numbers
  { word: "いち", meaning: "one", total: 0, right: 0, topic: ETopic.N5 },
  { word: "に", meaning: "two", total: 0, right: 0, topic: ETopic.N5 },
  { word: "さん", meaning: "three", total: 0, right: 0, topic: ETopic.N5 },
  { word: "よん", meaning: "four", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ご", meaning: "five", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ろく", meaning: "six", total: 0, right: 0, topic: ETopic.N5 },
  { word: "しち", meaning: "seven", total: 0, right: 0, topic: ETopic.N5 },
  { word: "はち", meaning: "eight", total: 0, right: 0, topic: ETopic.N5 },
  { word: "きゅう", meaning: "nine", total: 0, right: 0, topic: ETopic.N5 },
  { word: "じゅう", meaning: "ten", total: 0, right: 0, topic: ETopic.N5 },
  // Colors
  { word: "あか", meaning: "red", total: 0, right: 0, topic: ETopic.N5 },
  { word: "あお", meaning: "blue", total: 0, right: 0, topic: ETopic.N5 },
  { word: "しろ", meaning: "white", total: 0, right: 0, topic: ETopic.N5 },
  { word: "くろ", meaning: "black", total: 0, right: 0, topic: ETopic.N5 },
  { word: "きいろ", meaning: "yellow", total: 0, right: 0, topic: ETopic.N5 },
  // Days of the Week
  {
    word: "げつようび",
    meaning: "Monday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "かようび",
    meaning: "Tuesday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "すいようび",
    meaning: "Wednesday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "もくようび",
    meaning: "Thursday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "きんようび",
    meaning: "Friday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "どようび",
    meaning: "Saturday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "にちようび",
    meaning: "Sunday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  // Family
  {
    word: "おとうさん",
    meaning: "father",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "おかあさん",
    meaning: "mother",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "おにいさん",
    meaning: "older brother",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "おねえさん",
    meaning: "older sister",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "いもうと",
    meaning: "younger sister",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "おとうと",
    meaning: "younger brother",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "じいさん",
    meaning: "grandfather",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "ばあさん",
    meaning: "grandmother",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  // Animals
  { word: "いぬ", meaning: "dog", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ねこ", meaning: "cat", total: 0, right: 0, topic: ETopic.N5 },
  { word: "とり", meaning: "bird", total: 0, right: 0, topic: ETopic.N5 },
  { word: "さかな", meaning: "fish", total: 0, right: 0, topic: ETopic.N5 },
  { word: "うし", meaning: "cow", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ひつじ", meaning: "sheep", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ねずみ", meaning: "mouse", total: 0, right: 0, topic: ETopic.N5 },
  { word: "うま", meaning: "horse", total: 0, right: 0, topic: ETopic.N5 },
  // Food and Drink
  {
    word: "ごはん",
    meaning: "rice;meal",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "みず", meaning: "water", total: 0, right: 0, topic: ETopic.N5 },
  { word: "おさけ", meaning: "alcohol", total: 0, right: 0, topic: ETopic.N5 },
  { word: "おちゃ", meaning: "tea", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "こうちゃ",
    meaning: "black tea",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "ぎゅうにゅう",
    meaning: "cow's milk",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "パン", meaning: "bread", total: 0, right: 0, topic: ETopic.N5 },
  { word: "たまご", meaning: "egg", total: 0, right: 0, topic: ETopic.N5 },
  // Body Parts
  { word: "あたま", meaning: "head", total: 0, right: 0, topic: ETopic.N5 },
  { word: "かお", meaning: "face", total: 0, right: 0, topic: ETopic.N5 },
  { word: "くち", meaning: "mouth", total: 0, right: 0, topic: ETopic.N5 },
  { word: "め", meaning: "eye", total: 0, right: 0, topic: ETopic.N5 },
  { word: "て", meaning: "hand", total: 0, right: 0, topic: ETopic.N5 },
  { word: "あし", meaning: "leg", total: 0, right: 0, topic: ETopic.N5 },
  { word: "は", meaning: "tooth", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ひざ", meaning: "knee", total: 0, right: 0, topic: ETopic.N5 },
  // Places
  { word: "うち", meaning: "home", total: 0, right: 0, topic: ETopic.N5 },
  { word: "いえ", meaning: "house", total: 0, right: 0, topic: ETopic.N5 },
  { word: "がっこう", meaning: "school", total: 0, right: 0, topic: ETopic.N5 },
  { word: "いえ", meaning: "home", total: 0, right: 0, topic: ETopic.N5 },
  { word: "こうえん", meaning: "park", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "としょかん",
    meaning: "library",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "いえ", meaning: "home", total: 0, right: 0, topic: ETopic.N5 },
  { word: "おおきい", meaning: "big", total: 0, right: 0, topic: ETopic.N5 },
  // Basic Verbs
  { word: "する", meaning: "to do", total: 0, right: 0, topic: ETopic.N5 },
  { word: "いく", meaning: "to go", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "かえる",
    meaning: "to return;to go back",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "くる", meaning: "to come", total: 0, right: 0, topic: ETopic.N5 },
  { word: "みる", meaning: "to see", total: 0, right: 0, topic: ETopic.N5 },
  { word: "きく", meaning: "to listen", total: 0, right: 0, topic: ETopic.N5 },
  { word: "はなす", meaning: "to speak", total: 0, right: 0, topic: ETopic.N5 },
  { word: "たべる", meaning: "to eat", total: 0, right: 0, topic: ETopic.N5 },
  { word: "のむ", meaning: "to drink", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ねる", meaning: "to sleep", total: 0, right: 0, topic: ETopic.N5 },
  // Time
  { word: "じかん", meaning: "time", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "とき",
    meaning: "time;moment",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "いつ", meaning: "when", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "まいにち",
    meaning: "every day",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "あした", meaning: "tomorrow", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "きのう",
    meaning: "yesterday",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  // Directions
  { word: "みぎ", meaning: "right", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ひだり", meaning: "left", total: 0, right: 0, topic: ETopic.N5 },
  { word: "まえ", meaning: "front", total: 0, right: 0, topic: ETopic.N5 },
  { word: "うしろ", meaning: "back", total: 0, right: 0, topic: ETopic.N5 },
  { word: "うえ", meaning: "up;above", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "した",
    meaning: "down;below",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  // Daily Activities
  { word: "たべる", meaning: "to eat", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ねる", meaning: "to sleep", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "ぎょうざをやく",
    meaning: "to make dumplings",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "あさごはんをたべる",
    meaning: "to eat breakfast",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "てをあらう",
    meaning: "to wash hands",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "うたう", meaning: "to sing", total: 0, right: 0, topic: ETopic.N5 },
  // Descriptive Words
  { word: "あたたかい", meaning: "warm", total: 0, right: 0, topic: ETopic.N5 },
  { word: "さむい", meaning: "cold", total: 0, right: 0, topic: ETopic.N5 },
  { word: "おおきい", meaning: "big", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ちいさい", meaning: "small", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "たかい",
    meaning: "high;tall",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "ひくい",
    meaning: "low;short",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  // Actions
  { word: "する", meaning: "to do", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "かえる",
    meaning: "to return;to go back",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "くる", meaning: "to come", total: 0, right: 0, topic: ETopic.N5 },
  { word: "たべる", meaning: "to eat", total: 0, right: 0, topic: ETopic.N5 },
  { word: "のむ", meaning: "to drink", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ねる", meaning: "to sleep", total: 0, right: 0, topic: ETopic.N5 },
  // Travel
  { word: "くるま", meaning: "car", total: 0, right: 0, topic: ETopic.N5 },
  { word: "でんしゃ", meaning: "train", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "ひこうき",
    meaning: "airplane",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "じてんしゃ",
    meaning: "bicycle",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "バス", meaning: "bus", total: 0, right: 0, topic: ETopic.N5 },
  // Clothing
  { word: "ぼうし", meaning: "hat", total: 0, right: 0, topic: ETopic.N5 },
  { word: "くつ", meaning: "shoes", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "せびろ",
    meaning: "trousers;pants",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "ワンピース",
    meaning: "dress",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "シャツ", meaning: "shirt", total: 0, right: 0, topic: ETopic.N5 },
  // Common Objects
  { word: "かさ", meaning: "umbrella", total: 0, right: 0, topic: ETopic.N5 },
  { word: "かばん", meaning: "bag", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "じしょ",
    meaning: "dictionary",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "かぎ", meaning: "key", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "とけい",
    meaning: "clock;watch",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  // Feelings
  { word: "うれしい", meaning: "happy", total: 0, right: 0, topic: ETopic.N5 },
  { word: "かなしい", meaning: "sad", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "おそろしい",
    meaning: "scary",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "ねむい", meaning: "sleepy", total: 0, right: 0, topic: ETopic.N5 },
  { word: "いたい", meaning: "painful", total: 0, right: 0, topic: ETopic.N5 },
  // Others
  { word: "たまご", meaning: "egg", total: 0, right: 0, topic: ETopic.N5 },
  { word: "くつした", meaning: "socks", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ぼうし", meaning: "hat", total: 0, right: 0, topic: ETopic.N5 },
  { word: "てがみ", meaning: "letter", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ほん", meaning: "book", total: 0, right: 0, topic: ETopic.N5 },
  // Months
  {
    word: "いちがつ",
    meaning: "January",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  { word: "にがつ", meaning: "February", total: 0, right: 0, topic: ETopic.N5 },
  { word: "さんがつ", meaning: "March", total: 0, right: 0, topic: ETopic.N5 },
  { word: "しがつ", meaning: "April", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ごがつ", meaning: "May", total: 0, right: 0, topic: ETopic.N5 },
  { word: "ろくがつ", meaning: "June", total: 0, right: 0, topic: ETopic.N5 },
  { word: "しちがつ", meaning: "July", total: 0, right: 0, topic: ETopic.N5 },
  { word: "はちがつ", meaning: "August", total: 0, right: 0, topic: ETopic.N5 },
  {
    word: "くがつ",
    meaning: "September",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "じゅうがつ",
    meaning: "October",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "じゅういちがつ",
    meaning: "November",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
  {
    word: "じゅうにがつ",
    meaning: "December",
    total: 0,
    right: 0,
    topic: ETopic.N5,
  },
];

export const vocabularyAll: IWord[] = [
  ...vocabularyAnimals,
  ...vocabularyColors,
  ...vocabularyFood,
  ...vocabularyItems,
  ...vocabularyJobs,
  ...vocabularyNumbers,
  ...vocabularyPlaces,
  ...vocabularyProfessions,
  ...vocabularySchool,
  ...vocabularyShopping,
  ...vocabularySports,
  ...vocabularyTime,
  ...vocabularyTransportation,
  ...vocabularySubjects,
  ...vocabularyWeather,
  ...vocabularyFamily,
  ...vocabularyCountry,
  ...vocabularyTechnology,
  ...vocabularyTaste,
  ...vocabularyFeeling,
  ...vocabularyMusic,
  ...vocabularyMovie,
  ...vocabularyHouseholdItems,
  ...vocabularyMenu,
  ...vocabularyTown,
  ...vocabularyTrainStation,
  ...vocabularyHealth,
  ...vocabularyMovement,
  ...vocabularyClothing,
  ...vocabularyHumanLife,
  ...vocabularyVerbs,
  ...vocabularyN5,
];
