import {  IWord } from "../redux/features/words/slices";
import { ETopic } from "../types/topic.types";

export const vocabularyFamily: IWord[] = [
  {
    word: "ひと",
    kanji: "人",
    meaning: "person",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "かぞく",
    kanji: "家族",
    meaning: "family",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "おとうさん",
    kanji: "お父さん",
    meaning: "father",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "おかあさん",
    kanji: "お母さん",
    meaning: "mother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "あに",
    kanji: "兄",
    meaning: "older brother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "あね",
    kanji: "姉",
    meaning: "older sister",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "おとうと",
    kanji: "弟",
    meaning: "younger brother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "いもうと",
    kanji: "妹",
    meaning: "younger sister",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "こども",
    kanji: "子供",
    meaning: "child",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "むすこ",
    kanji: "息子",
    meaning: "son",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "むすめ",
    kanji: "娘",
    meaning: "daughter",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "じいさん",
    kanji: "祖父さん",
    meaning: "grandfather",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "ばあさん",
    kanji: "祖母さん",
    meaning: "grandmother",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
  {
    word: "いとこ",
    kanji: "いとこ",
    meaning: "cousin",
    total: 0,
    right: 0,
    topic: ETopic.FAMILY,
  },
];
export const vocabularyWeather: IWord[] = [
  {
    word: "てんき",
    kanji: "天気",
    meaning: "weather",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "あめ",
    kanji: "雨",
    meaning: "rain",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "ゆき",
    kanji: "雪",
    meaning: "snow",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "くもり",
    kanji: "曇り",
    meaning: "cloudy",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "はれ",
    kanji: "晴れ",
    meaning: "sunny",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "かぜ",
    kanji: "風",
    meaning: "wind",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "かみなり",
    kanji: "雷",
    meaning: "thunder",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "たいふう",
    kanji: "台風",
    meaning: "typhoon",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "あらし",
    kanji: "嵐",
    meaning: "storm",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
  {
    word: "あらし",
    kanji: "嵐",
    meaning: "storm",
    total: 0,
    right: 0,
    topic: ETopic.WEATHER,
  },
];
export const vocabularyFood: IWord[] = [
  {
    word: "たべもの",
    kanji: "食べ物",
    meaning: "food",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ごはん",
    kanji: "ご飯",
    meaning: "cooked rice",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "みそしる",
    kanji: "味噌汁",
    meaning: "miso soup",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "さかな",
    kanji: "魚",
    meaning: "fish",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "にく",
    kanji: "肉",
    meaning: "meat",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "やさい",
    kanji: "野菜",
    meaning: "vegetable",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "くだもの",
    kanji: "果物",
    meaning: "fruit",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "パン",
    kanji: "パン",
    meaning: "bread",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "ごはん",
    kanji: "ご飯",
    meaning: "cooked rice",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "たまご",
    kanji: "卵",
    meaning: "egg",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "にく",
    kanji: "肉",
    meaning: "meat",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "さとう",
    kanji: "砂糖",
    meaning: "sugar",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "しお",
    kanji: "塩",
    meaning: "salt",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
  {
    word: "おかし",
    kanji: "お菓子",
    meaning: "sweets",
    total: 0,
    right: 0,
    topic: ETopic.FOOD,
  },
];
export const vocabularyTransportation: IWord[] = [
  {
    word: "くるま",
    kanji: "車",
    meaning: "car",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "じてんしゃ",
    kanji: "自転車",
    meaning: "bicycle",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "でんしゃ",
    kanji: "電車",
    meaning: "train",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "バス",
    kanji: "バス",
    meaning: "bus",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "てんしゃ",
    kanji: "電車",
    meaning: "tram",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "くうこう",
    kanji: "空港",
    meaning: "airport",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
  {
    word: "ふね",
    kanji: "船",
    meaning: "boat",
    total: 0,
    right: 0,
    topic: ETopic.TRANSPORTATION,
  },
];

export const vocabularyShopping: IWord[] = [
  {
    word: "かいもの",
    kanji: "買い物",
    meaning: "shopping",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "デパート",
    kanji: "デパート",
    meaning: "department store",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "しょうしょ",
    kanji: "商店",
    meaning: "shop",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "えいが",
    kanji: "映画",
    meaning: "movie",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "みせ",
    kanji: "店",
    meaning: "store",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "レストラン",
    kanji: "レストラン",
    meaning: "restaurant",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "スーパー",
    kanji: "スーパー",
    meaning: "supermarket",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
  {
    word: "レジ",
    kanji: "レジ",
    meaning: "cash register",
    total: 0,
    right: 0,
    topic: ETopic.SHOPPING,
  },
];

export const vocabularySports: IWord[] = [
  {
    word: "スポーツ",
    kanji: "スポーツ",
    meaning: "sports",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "サッカー",
    kanji: "サッカー",
    meaning: "soccer",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "テニス",
    kanji: "テニス",
    meaning: "tennis",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "バスケットボール",
    kanji: "バスケットボール",
    meaning: "basketball",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "バレーボール",
    kanji: "バレーボール",
    meaning: "volleyball",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "野球",
    kanji: "野球",
    meaning: "baseball",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "ゴルフ",
    kanji: "ゴルフ",
    meaning: "golf",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "スキー",
    kanji: "スキー",
    meaning: "skiing",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "スケート",
    kanji: "スケート",
    meaning: "skating",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
  {
    word: "サーフィン",
    kanji: "サーフィン",
    meaning: "surfing",
    total: 0,
    right: 0,
    topic: ETopic.SPORTS,
  },
];

export const vocabularySchool: IWord[] = [
  {
    word: "がっこう",
    kanji: "学校",
    meaning: "school",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "せんせい",
    kanji: "先生",
    meaning: "teacher",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "がくせい",
    kanji: "学生",
    meaning: "student",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "きょうしつ",
    kanji: "教室",
    meaning: "classroom",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "ほん",
    kanji: "本",
    meaning: "book",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "とけい",
    kanji: "時計",
    meaning: "clock",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "ペン",
    kanji: "ペン",
    meaning: "pen",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "ノート",
    kanji: "ノート",
    meaning: "notebook",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "しけん",
    kanji: "試験",
    meaning: "exam",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
  {
    word: "かばん",
    kanji: "鞄",
    meaning: "bag",
    total: 0,
    right: 0,
    topic: ETopic.SCHOOL,
  },
];

export const vocabularyJobs: IWord[] = [
  {
    word: "しごと",
    kanji: "仕事",
    meaning: "job",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "かいしゃいん",
    kanji: "会社員",
    meaning: "company employee",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "せんせい",
    kanji: "先生",
    meaning: "teacher",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "いしゃ",
    kanji: "医者",
    meaning: "doctor",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "けんちくか",
    kanji: "建築家",
    meaning: "architect",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "かしゅ",
    kanji: "歌手",
    meaning: "singer",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "えいがか",
    kanji: "映画家",
    meaning: "filmmaker",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "べんごし",
    kanji: "弁護士",
    meaning: "lawyer",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "こうむいん",
    kanji: "公務員",
    meaning: "public servant",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
  {
    word: "だいがくきょうし",
    kanji: "大学教師",
    meaning: "university professor",
    total: 0,
    right: 0,
    topic: ETopic.JOBS,
  },
];

export const vocabularyAnimals: IWord[] = [
  {
    word: "どうぶつ",
    kanji: "動物",
    meaning: "animal",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "いぬ",
    kanji: "犬",
    meaning: "dog",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ねこ",
    kanji: "猫",
    meaning: "cat",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "うさぎ",
    kanji: "うさぎ",
    meaning: "rabbit",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "とり",
    kanji: "鳥",
    meaning: "bird",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "さる",
    kanji: "猿",
    meaning: "monkey",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ぞう",
    kanji: "象",
    meaning: "elephant",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ひつじ",
    kanji: "羊",
    meaning: "sheep",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "ねずみ",
    kanji: "鼠",
    meaning: "mouse",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
  {
    word: "うし",
    kanji: "牛",
    meaning: "cow",
    total: 0,
    right: 0,
    topic: ETopic.ANIMALS,
  },
];

export const vocabularyItems: IWord[] = [
  {
    word: "もの",
    kanji: "物",
    meaning: "thing",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "えんぴつ",
    kanji: "鉛筆",
    meaning: "pencil",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "ペン",
    kanji: "ペン",
    meaning: "pen",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "ほん",
    kanji: "本",
    meaning: "book",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "かさ",
    kanji: "傘",
    meaning: "umbrella",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "とけい",
    kanji: "時計",
    meaning: "watch",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "でんしゃ",
    kanji: "電車",
    meaning: "train",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "くるま",
    kanji: "車",
    meaning: "car",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "てちょう",
    kanji: "手帳",
    meaning: "notebook",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "けしゴム",
    kanji: "消しゴム",
    meaning: "eraser",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
  {
    word: "かぎ",
    kanji: "鍵",
    meaning: "key",
    total: 0,
    right: 0,
    topic: ETopic.ITEMS,
  },
];

export const vocabularyProfessions: IWord[] = [
  {
    word: "かいしゃいん",
    kanji: "会社員",
    meaning: "company employee",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "せんせい",
    kanji: "先生",
    meaning: "teacher",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "べんごし",
    kanji: "弁護士",
    meaning: "lawyer",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "いしゃ",
    kanji: "医者",
    meaning: "doctor",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "けんちくか",
    kanji: "建築家",
    meaning: "architect",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "かしゅ",
    kanji: "歌手",
    meaning: "singer",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "かいがいりょこうがいしゃいん",
    kanji: "海外旅行会社員",
    meaning: "travel agency employee",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "エンジニア",
    kanji: "エンジニア",
    meaning: "engineer",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "パイロット",
    kanji: "パイロット",
    meaning: "pilot",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
  {
    word: "おかしや",
    kanji: "お菓子屋",
    meaning: "confectioner",
    total: 0,
    right: 0,
    topic: ETopic.PROFESSIONS,
  },
];

export const vocabularySubjects: IWord[] = [
  {
    word: "れきし",
    kanji: "歴史",
    meaning: "history",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "さんすう",
    kanji: "算数",
    meaning: "mathematics",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "けいざい",
    kanji: "経済",
    meaning: "economics",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "りか",
    kanji: "理科",
    meaning: "science",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "ぶんがく",
    kanji: "文学",
    meaning: "literature",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "かがく",
    kanji: "化学",
    meaning: "chemistry",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "ぎじゅつ",
    kanji: "技術",
    meaning: "technology",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "えいご",
    kanji: "英語",
    meaning: "English",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "にほんご",
    kanji: "日本語",
    meaning: "Japanese",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
  {
    word: "じょうほうがく",
    kanji: "情報学",
    meaning: "informatics",
    total: 0,
    right: 0,
    topic: ETopic.SUBJECTS,
  },
];

export const vocabularyPlaces: IWord[] = [
  {
    word: "えき",
    kanji: "駅",
    meaning: "station",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "こうえん",
    kanji: "公園",
    meaning: "park",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "うみ",
    kanji: "海",
    meaning: "sea",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "いえ",
    kanji: "家",
    meaning: "house",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "やま",
    kanji: "山",
    meaning: "mountain",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "ほんや",
    kanji: "本屋",
    meaning: "bookstore",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "びょういん",
    kanji: "病院",
    meaning: "hospital",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "えいがかん",
    kanji: "映画館",
    meaning: "movie theater",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "まち",
    kanji: "町",
    meaning: "town",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
  {
    word: "うみべ",
    kanji: "海辺",
    meaning: "beach",
    total: 0,
    right: 0,
    topic: ETopic.PLACES,
  },
];

export const vocabularyNumbers: IWord[] = [
  {
    word: "じゅういち",
    kanji: "十一",
    meaning: "eleven",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "にじゅう",
    kanji: "二十",
    meaning: "twenty",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さんじゅう",
    kanji: "三十",
    meaning: "thirty",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "よんじゅう",
    kanji: "四十",
    meaning: "forty",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ごじゅう",
    kanji: "五十",
    meaning: "fifty",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ろくじゅう",
    kanji: "六十",
    meaning: "sixty",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ななじゅう",
    kanji: "七十",
    meaning: "seventy",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "はちじゅう",
    kanji: "八十",
    meaning: "eighty",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "きゅうじゅう",
    kanji: "九十",
    meaning: "ninety",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ひゃくいち",
    kanji: "百一",
    meaning: "one hundred one",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さんびゃくごじゅうに",
    kanji: "三百五十二",
    meaning: "three hundred fifty-two",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "せんはっぴゃくじゅう",
    kanji: "千八百十",
    meaning: "one thousand eight hundred ten",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ごせん",
    kanji: "五千",
    meaning: "five thousand",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ななせんごひゃく",
    kanji: "七千五百",
    meaning: "seven thousand five hundred",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "じゅうまん",
    kanji: "十万",
    meaning: "one hundred thousand",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さんびゃくまん",
    kanji: "三百万",
    meaning: "three million",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "いち",
    kanji: "一",
    meaning: "one",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "に",
    kanji: "二",
    meaning: "two",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "さん",
    kanji: "三",
    meaning: "three",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "し",
    kanji: "四",
    meaning: "four",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ご",
    kanji: "五",
    meaning: "five",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ろく",
    kanji: "六",
    meaning: "six",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "しち",
    kanji: "七",
    meaning: "seven",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "はち",
    kanji: "八",
    meaning: "eight",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "きゅう",
    kanji: "九",
    meaning: "nine",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "じゅう",
    kanji: "十",
    meaning: "ten",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ひゃく",
    kanji: "百",
    meaning: "hundred",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "せん",
    kanji: "千",
    meaning: "thousand",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "まん",
    kanji: "万",
    meaning: "ten thousand",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "おく",
    kanji: "億",
    meaning: "hundred million",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "てん",
    kanji: "点",
    meaning: "point",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
  {
    word: "ぜろ",
    kanji: "零",
    meaning: "zero",
    total: 0,
    right: 0,
    topic: ETopic.NUMBERS,
  },
];

export const vocabularyColors: IWord[] = [
  {
    word: "あか",
    kanji: "赤",
    meaning: "red",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "あお",
    kanji: "青",
    meaning: "blue",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "きいろ",
    kanji: "黄色",
    meaning: "yellow",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "みどり",
    kanji: "緑",
    meaning: "green",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "しろ",
    kanji: "白",
    meaning: "white",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "くろ",
    kanji: "黒",
    meaning: "black",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "むらさき",
    kanji: "紫",
    meaning: "purple",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "ピンク",
    kanji: "ピンク",
    meaning: "pink",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "オレンジ",
    kanji: "オレンジ",
    meaning: "orange",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
  {
    word: "ブラウン",
    kanji: "ブラウン",
    meaning: "brown",
    total: 0,
    right: 0,
    topic: ETopic.COLORS,
  },
];

export const vocabularyTime: IWord[] = [
  {
    word: "じかん",
    kanji: "時間",
    meaning: "time",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ひ",
    kanji: "日",
    meaning: "day",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "しゅう",
    kanji: "週",
    meaning: "week",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "つき",
    kanji: "月",
    meaning: "month",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ねん",
    kanji: "年",
    meaning: "year",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "あさ",
    kanji: "朝",
    meaning: "morning",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ひる",
    kanji: "昼",
    meaning: "noon",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ばん",
    kanji: "晩",
    meaning: "evening",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ごご",
    kanji: "午後",
    meaning: "afternoon",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
  {
    word: "ごぜん",
    kanji: "午前",
    meaning: "morning",
    total: 0,
    right: 0,
    topic: ETopic.TIME,
  },
];

export const vocabularyAll: IWord[] = [
  ...vocabularyAnimals,
  ...vocabularyColors,
  ...vocabularyFood,
  ...vocabularyItems,
  ...vocabularyJobs,
  ...vocabularyNumbers,
  ...vocabularyPlaces,
  ...vocabularyProfessions,
  ...vocabularySchool,
  ...vocabularyShopping,
  ...vocabularySports,
  ...vocabularyTime,
  ...vocabularyTransportation,
  ...vocabularySubjects,
  ...vocabularyWeather,
  ...vocabularyFamily,
];
