export enum ETopic {
  All = "0",
  ANIMALS = "animals",
  COLORS = "colors",
  FOOD = "food",
  ITEMS = "items",
  JOBS = "jobs",
  NUMBERS = "numbers",
  PLACES = "places",
  PROFESSIONS = "professions",
  SCHOOL = "school",
  SHOPPING = "shopping",
  SPORTS = "sports",
  TIME = "time",
  TRANSPORTATION = "transportation",
  SUBJECTS = "subjects",
  WEATHER = "weather",
  FAMILY = "family",
}
